### ISSUE TITLE
Getting error while running workflow

### ISSUE THREAD

**Issue by narula0781** [machine-learning-apps/ml-template-azure#11]
I used the steps mentioned in youtube video.
But my workflow failed with following error.
After talking to Ashish , I got to know , I need to run following CLI commands.

az provider register --namespace Microsoft.MachineLearningServices
az provider register --namespace Microsoft.MachineLearning
az provider register --namespace Microsoft.Compute

This should be covered in youtube video and documentation a well.

Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
Exception Details:
	Error Code: Conflict
	Message: ***'error': ***'code': 'MissingSubscriptionRegistration', 'message': "The subscription is not registered to use namespace 'Microsoft.MachineLearningServices'. See https://aka.ms/rps-not-found for how to register subscriptions.", 'details': [***'code': 'MissingSubscriptionRegistration', 'target': 'Microsoft.MachineLearningServices', 'message': "The subscription is not registered to use namespace 'Microsoft.MachineLearningServices'. See https://aka.ms/rps-not-found for how to register subscriptions."***]***
	ErrorResponse 
***
    "error": ***
        "message": "Unable to create the workspace. At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details."
    ***
***

Thanks,
Manish

**Comment by marvinbuss** [comment]
@narula0781 Thanks for submitting the issue. Have you seen this section: https://github.com/machine-learning-apps/ml-template-azure#known-issues ?
We can add more details, so that it also covers `Microsoft.MachineLearningServices`, `Microsoft.MachineLearning` and `Microsoft.Compute`.
