### ISSUE TITLE
Adding a list of files to registermodel.json config

### ISSUE THREAD

**Issue by an185144** [machine-learning-apps/ml-template-azure#12]
This is probably related to https://github.com/Azure/aml-registermodel/issues/27. Is there a way to add multiple files to registermodel.json config (or any other way) without having to pickle them into a single file? Would it accept a list of files?

**Comment by marvinbuss** [comment]
@an185144 I added a solution to this issue: https://github.com/Azure/aml-registermodel/issues/27
I hope this helps!
