### ISSUE TITLE
Submit training run fails while installing package 'conda-forge::cycler-0.11.0-pyhd8ed1ab_0'.

### ISSUE THREAD

**Issue by RajdeepBiswas** [machine-learning-apps/ml-template-azure#18]
### From the logs:
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::cycler-0.11.0-pyhd8ed1ab_0'.
FileNotFoundError(2, "No such file or directory: '/azureml-envs/azureml_1767a447844ba221bf5dc7377e1011f3/bin/python3.6'")
Attempting to roll back.

done

FileNotFoundError(2, "No such file or directory: '/azureml-envs/azureml_1767a447844ba221bf5dc7377e1011f3/bin/python3.6'")

**Comment by marvinbuss** [comment]
Hi @RajdeepBiswas, Is this related to the package that you are trying to install?
Did the installation succeed before? Which version of the GH Action are you using?

**Comment by rarora1979** [comment]
Followed all the steps given in the video - 
http://www.youtube.com/watch?v=bmFr0LYo_6o

getting the error - 

[91m
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::cycler-0.11.0-pyhd8ed1ab_0'.
FileNotFoundError(2, "No such file or directory: '/azureml-envs/azureml_1767a447844ba221bf5dc7377e1011f3/bin/python3.6'")
Attempting to roll back.

![image](https://user-images.githubusercontent.com/92135137/142925003-5b6b121b-4153-40b8-8e79-47330bafddb0.png)

excerpt from the logs - 
Executing transaction: ...working... failed
[91m
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::cycler-0.11.0-pyhd8ed1ab_0'.
FileNotFoundError(2, "No such file or directory: '/azureml-envs/azureml_1767a447844ba221bf5dc7377e1011f3/bin/python3.6'")
Attempting to roll back.

[0mRolling back transaction: ...working... done
[91m
FileNotFoundError(2, "No such file or directory: '/azureml-envs/azureml_1767a447844ba221bf5dc7377e1011f3/bin/python3.6'")


[0mThe command '/bin/sh -c ldconfig /usr/local/cuda/lib64/stubs && conda env create -p /azureml-envs/azureml_1767a447844ba221bf5dc7377e1011f3 -f azureml-environment-setup/mutated_conda_dependencies.yml && rm -rf "$HOME/.cache/pip" && conda clean -aqy && CONDA_ROOT_DIR=$(conda info --root) && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} + && ldconfig' returned a non-zero code: 1
2021/11/22 19:00:05 Container failed during run: acb_step_0. No retries remaining.
failed to run step ID: acb_step_0: exit status 1

Run ID: ca1 failed after 1h7m56s. Error: failed during run, err: exit status 1

**Comment by malikamalik** [comment]
I am getting the same error. Did you find a fix, @rarora1979

**Comment by marvinbuss** [comment]
Quick update: this is due to the environment specifications. Updating the python packages is required. I already have done this here and I will merge this back into the main repo later this week.
https://github.com/malikamalik/quicktest
