### ISSUE TITLE
Docs issue: Ambiguous description in setting the workspace name

### ISSUE THREAD

**Issue by sasever** [machine-learning-apps/ml-template-azure#2]
ReadMe.md, Getting Started, 4. Define your workspace parameters
Below sentence is ambiguous:
"Change the name parameter to the name of your workspace, if you have already created one or choose any name, if you want the Action to create a new workpace."

Change like below can be more clear:
"If you already have an Azure ML Workspace under that resource group, change the name parameter to the name of your workspace,  if you want the Action to create a new workspace  in that resource group, pick a name for your new workspace, and assign it to the name parameter."

**Comment by marvinbuss** [comment]
Will be changed in the README. Thanks for providing the feedback. This will be changed in the next release. There is already a new branch, which includes the changes.

**Comment by marvinbuss** [comment]
@awmatheson I cannot add the project to this issue. Can you check, whether I have access?
