### ISSUE TITLE
Actions Tab Documentation

### ISSUE THREAD

**Issue by marvinbuss** [machine-learning-apps/ml-template-azure#5]
Add more details in the README: 
- [ ] Show users how to get to the actions tab
- [ ] Show users how to create secrets, if a service principle has already been created
- [ ] Add a comment that mentions that the first run takes a little longer and mention why it is taking so long

**Comment by aronchick** [comment]
Finished #1 and #3 but not sure how to tackle #2

**Comment by aronchick** [comment]
cc @marvinbuss
